id = "08aa283e-34ee-47d4-83bc-4c4311a9c85f"
created_at = "2026-06-05T23:14:28.261675600+00:00"
title = "Expressive ticket query and ordering contract"
state = "draft"
component = "ticket"
parent = "8074d6f7-b888-4e57-95e6-06dde96384b8"
scope = "public"
slug = "ticket-query/expressive-query-and-ordering"
type = "specification"
