id = "2b0ce814-0c22-42fa-8a89-f123660690e8"
created_at = "2026-07-25T22:15:19.728458100+00:00"
title = "Ticket move-planner invisible-reference fixture visibility"
state = "draft"
component = "ticket"
scope = "internal"
slug = "ticket-api/move-planner/invisible-reference-fixture-visibility"
tickets = ["d5771b88-ca1d-41b2-8b59-0c911a34b37f"]
type = "specification"
