id = "da89c1b5-3237-4e58-a71b-d729990adf35"
created_at = "2026-07-29T17:36:30.864132200+00:00"
title = "Session merge and pickup"
state = "draft"
component = "session"
slug = "c737328d-session-merge-pickup"
type = "specification"
