id = "4114d8c1-0abc-4464-ae51-35b026690f0a"
created_at = "2026-09-05T17:04:40.586116600+00:00"
title = "Feedback Analytics Schema Migration"
state = "draft"
component = "feedback"
parent = "835fbbfe-5eb5-4f15-a1a6-35330030813d"
scope = "internal"
slug = "feedback/analytics/migration"
type = "specification"
