id = "1d62442b-61dc-4eeb-9b7c-e933f84470f2"
created_at = "2026-06-05T13:54:41.582020700+00:00"
title = "ticket-api state transition path unification"
state = "draft"
component = "ticket"
scope = "internal"
slug = "ticket-api/state-transition-path-unification"
type = "specification"
