id = "a28a88db-2b41-49d2-897c-6dbcdb313255"
created_at = "2026-06-27T10:50:33.887196800+00:00"
title = "Minimal bootstrapper and selective rule loading"
state = "draft"
component = "rule"
parent = "8c880efc-7083-4e1d-bf06-96b8254be913"
scope = "internal"
slug = "memory-api/session-api/minimal-bootstrapper-selective-loading"
type = "specification"
