id = "8074d6f7-b888-4e57-95e6-06dde96384b8"
created_at = "2026-04-20T21:58:14.618692800+00:00"
title = "memory-api"
state = "draft"
component = "memory-kernel"
scope = "public"
slug = "memory-api"
type = "specification"
