id = "0b1888f2-7e59-45fb-95d8-1bf14ff7747f"
created_at = "2026-05-17T16:42:36.919073300+00:00"
title = "Ancestor Workspace Ticket References for Child-Workspace Dependencies"
state = "draft"
component = "ticket"
parent = "ae5ef697-0ee5-4f74-9dca-2cb268290dae"
scope = "public"
slug = "ticket-api/workspaces/ancestor-dependency-visibility"
type = "specification"
