id = "c095bb6b-f343-4ae9-9282-0d51a06d099a"
created_at = "2026-09-25T14:35:02.553606500+00:00"
title = "Kernel Cross-Repository Move Safety"
state = "draft"
component = "memory-kernel"
parent = "7487a6b5-39c6-4114-a697-6ed0556e888e"
scope = "internal"
slug = "storage/cross-repository-move-safety"
type = "specification"
