id = "ed877ff1-37e4-41fe-aa79-87c6daa58be9"
created_at = "2026-09-05T17:04:36.133134100+00:00"
title = "Feedback Analytics Core"
state = "draft"
component = "feedback"
parent = "835fbbfe-5eb5-4f15-a1a6-35330030813d"
scope = "internal"
slug = "feedback/analytics/core"
type = "specification"
