id = "c1d13a73-3265-42e1-8da0-5c44ef7b61ff"
created_at = "2026-08-23T14:48:06.336405800+00:00"
title = "Worktree Provisioning Policy"
state = "draft"
component = "workflow-tools"
parent = "fa6e85c8-866c-4d53-bb50-b78bd651e8ce"
scope = "internal"
slug = "worktree-control/component-pilot/provisioning-policy"
type = "specification"
