id = "66fbd896-19d4-4bb7-898c-7cdc76375a5e"
created_at = "2026-08-23T15:13:04.038436800+00:00"
title = "Worktree Git Operations"
state = "draft"
component = "workflow-tools"
parent = "fa6e85c8-866c-4d53-bb50-b78bd651e8ce"
scope = "internal"
slug = "worktree-control/git-operations"
type = "specification"
