id = "267acfdc-7df4-4090-9f17-7d6d71232814"
created_at = "2026-04-20T21:58:15.081760300+00:00"
title = "entity"
state = "draft"
code_refs = [{ file = "crates/memory-api/src/model/entity.rs", kind = "struct", line_end = 16, line_start = 11, symbol = "EntityManifest" }, { file = "crates/memory-api/src/model/entity.rs", kind = "impl", line_end = 26, line_start = 18, symbol = "EntityManifest" }]
component = "memory-kernel"
parent = "8074d6f7-b888-4e57-95e6-06dde96384b8"
scope = "public"
slug = "memory-api/model/entity"
type = "specification"
