id = "43b9a6ac-89d6-479a-876b-3d1a5e2d39e6"
created_at = "2026-07-27T20:58:58.393632200+00:00"
title = "Multi-Client Guidance Rendering"
state = "draft"
component = "rule"
slug = "rule-system/multi-client-guidance-rendering"
type = "specification"
